#quarkus.datasource.devservices.reuse=true
#quarkus.datasource.devservices.show-logs=false
#quarkus.datasource.devservices.devservices.enabled=false
#quarkus.datasource.db-kind=mysql
#quarkus.datasource.jdbc.url=jdbc:mysql://localhost:3306/mydb?allowPublicKeyRetrieval=true
#quarkus.datasource.username=myuser
#quarkus.datasource.password=mypassword

quarkus.hibernate-orm.log.sql=true
quarkus.hibernate-orm.schema-management.strategy=drop-and-create

# admin
quarkus.http.auth.basic=true

quarkus.security.users.embedded.enabled=true

quarkus.security.users.embedded.plain-text=true

quarkus.security.users.embedded.users.alice=alice
quarkus.security.users.embedded.roles.alice=admin

quarkus.security.users.embedded.users.bob=bob
quarkus.security.users.embedded.roles.bob=user